version: '3.9'

services:
  api:
    build: "./"
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://armanyusuf12:arman123@cluster0.apqjjj0.mongodb.net/DevTime-API
      - WT_SECRET=supersecretkey
      - PORT=5000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    
  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    
volumes:
  mongo-data: